# PROD environment

app:
  message: This is the property file of the ${spring.application.name} specific to PROD Environment
server:
  port: 8080

spring:
  datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: <MYSQL_URL>
  username: <USERNAME>
  password: <PASSWORD>